# Make sure to increment the value when version is released
pre_rel_version: '12'

map_component_to_distgit:
  cinder:
    dist_git: 'openstack-cinder'
  glance_store:
    dist_git: 'python-glance-store'
  glance:
    dist_git: 'openstack-glance'
  manila:
    dist_git: 'openstack-manila'
  neutron:
    dist_git: 'openstack-neutron'
  neutron-lbaas:
    dist_git: 'openstack-neutron-lbaas'
  nova:
    dist_git: 'openstack-nova'
  octavia:
    dist_git: 'openstack-octavia'
  odl-aaa:
    dist_git: 'opendaylight'
  odl-autorelease:
    dist_git: 'opendaylight'
  odl-controller:
    dist_git: 'opendaylight'
  odl-dlux:
    dist_git: 'opendaylight'
  odl-genius:
    dist_git: 'opendaylight'
  odl-infrautils:
    dist_git: 'opendaylight'
  odl-lispflowmapping:
    dist_git: 'opendaylight'
  odl-mdsal:
    dist_git: 'opendaylight'
  odl-netconf:
    dist_git: 'opendaylight'
  odl-netvirt:
    dist_git: 'opendaylight'
  odl-neutron:
    dist_git: 'opendaylight'
  odl-odlparent:
    dist_git: 'opendaylight'
  odl-openflowjava:
    dist_git: 'opendaylight'
  odl-openflowplugin:
    dist_git: 'opendaylight'
  odl-ovsdb:
    dist_git: 'opendaylight'
  odl-sfc:
    dist_git: 'opendaylight'
  odl-yangtools:
    dist_git: 'opendaylight'
  python-cinderclient:
    dist_git: 'python-cinderclient'
  python-glanceclient:
    dist_git: 'python-glanceclient'
  python-manilaclient:
    dist_git: 'python-manilaclient'
  python-neutronclient:
    dist_git: 'python-neutronclient'
  python-novaclient:
    dist_git: 'python-novaclient'
  python-os-brick:
    dist_git: 'python-os-brick'
  python-saharaclient:
    dist_git: 'python-saharaclient'
  sahara:
    dist_git: 'openstack-sahara'
  swift:
    dist_git: 'openstack-swift'
